# Generated by Django 6.0.3 on 2026-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="humidity_threshold",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="run",
            name="light_threshold",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="run",
            name="temp_threshold",
            field=models.FloatField(default=0.0),
        ),
    ]
