# Generated by Django 6.0.3 on 2026-04-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="name",
            new_name="object",
        ),
        migrations.RemoveField(
            model_name="run",
            name="is_active",
        ),
    ]
