# Generated by Django 6.0.3 on 2026-04-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0002_rename_name_run_object_remove_run_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="blackbox.run",
            ),
        ),
    ]
