# Generated by Django 6.0.3 on 2026-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbox', '0002_run_humidity_threshold_run_light_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='box_open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='shock_count',
            field=models.IntegerField(default=0),
        ),
    ]
