# Generated by Django 6.0.3 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbox', '0003_run_box_open_count_run_shock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='humi_exceeded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='light_exceeded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='temp_exceeded',
            field=models.IntegerField(default=0),
        ),
    ]
