# Generated by Django 6.0.3 on 2026-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0003_alter_sensorreading_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="event_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
