# Generated by Django 6.0.3 on 2026-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0004_sensorreading_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
