# Generated by Django 6.0.3 on 2026-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0005_run_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
