# Generated by Django 6.0.3 on 2026-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackbox", "0006_alter_sensorreading_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="firebase_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
